<program> ::= <statement> +
<statement> ::= <withdrawal> | <deposit> | <create_account> | <balance>
<balance> ::= "BALANCE" <account>
<create_account> ::= "CREATE" "FIRSTNAME" <name> "LASTNAME" <name> | 
    <create_account> "BALANCE" <number> | <create_account> "ACCOUNT" <account_identifier>
<deposit> ::= "DEPOSIT" <account> <number>
<withdrawal> ::= "WITHDRAW" <account> <number>
<account_identifier> ::= <letter> <letter> <digit> <digit> <digit> <digit> <digit> <digit>
<name> ::= <letter> +
<number> ::= <integer> | <decimal>
<decimal> ::= <integer> | <integer> "." <integer>
<integer> ::= <digit> | <digit> <integer>
<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<letter> ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | 
    "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | 
    "w" | "x" | "y" | "z" | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | 
    "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | 
    "U" | "V" | "W" | "X" | "Y" | "Z"